version: 1
builder:
  configs:
    - platform: macosSpm
      documentation_targets:
        - SwiftROS2
        - SwiftROS2Transport
        - SwiftROS2Messages
        - SwiftROS2Wire
        - SwiftROS2CDR
