/// Emits the generated RCL *action* typesupport registry
/// (`Generated/crcl_action_registry.c` + `include/Generated/crcl_action_registry.h`).
///
/// Per the M8 serialize-shim design, the generator emits no per-field action
/// marshalling — only a registry: per `.action` type, getters for the action
/// typesupport (`ROSIDL_GET_ACTION_TYPE_SUPPORT`) and, for each of the five
/// rosidl-synthesized wrapper message roles (`SendGoal_Request`,
/// `SendGoal_Response`, `GetResult_Request`, `GetResult_Response`,
/// `FeedbackMessage`), the *message* typesupport
/// (`ROSIDL_GET_MSG_TYPE_SUPPORT` with the `action` subfolder) and the rosidl
/// `__create` / `__destroy` pairs. The entry struct (`crcl_action_entry_t`)
/// and the lookup declaration live in the hand-written
/// `Sources/CRclBridge/include/crcl_action_registry.h`; the generated file
/// only fills the table and implements the lookup.
public enum CActionRegistryEmitter {
    /// Identifies one `.action` type to register. Sorting / lookup key is the
    /// canonical ROS action name `"<package>/action/<TypeName>"`.
    public struct ActionRef: Equatable, Sendable {
        public let package: String
        public let typeName: String

        public init(package: String, typeName: String) {
            self.package = package
            self.typeName = typeName
        }

        public var rosName: String { "\(package)/action/\(typeName)" }
    }

    /// The five wrapper message roles every rosidl action synthesizes. Order
    /// matches the `crcl_action_entry_t` field order.
    private static let wrapperRoles: [(field: String, suffix: String, cType: String)] = [
        (field: "send_goal_request", suffix: "sg_req", cType: "SendGoal_Request"),
        (field: "send_goal_response", suffix: "sg_res", cType: "SendGoal_Response"),
        (field: "get_result_request", suffix: "gr_req", cType: "GetResult_Request"),
        (field: "get_result_response", suffix: "gr_res", cType: "GetResult_Response"),
        (field: "feedback_message", suffix: "fb_msg", cType: "FeedbackMessage"),
    ]

    /// Emits `crcl_action_registry.c`. Entries are sorted by canonical ROS
    /// name for deterministic regeneration.
    public static func emit(_ actions: [ActionRef]) -> String {
        let sorted = actions.sorted { $0.rosName < $1.rosName }
        var lines: [String] = []
        lines.append("// Generated by swift-ros2-gen — DO NOT EDIT.")
        lines.append("")
        lines.append("#include \"Generated/crcl_action_registry.h\"")
        lines.append("")
        lines.append("#include \"crcl_action_registry.h\"")
        lines.append("")
        for include in umbrellaIncludes(sorted) {
            lines.append("#include <\(include)>")
        }
        lines.append("#include <rosidl_runtime_c/action_type_support_struct.h>")
        lines.append("#include <rosidl_runtime_c/message_type_support_struct.h>")
        lines.append("#include <stddef.h>")
        lines.append("#include <string.h>")
        lines.append("")
        for action in sorted {
            lines.append(contentsOf: wrapperBlock(action))
            lines.append("")
        }
        lines.append("static const crcl_action_entry_t crcl_action_entries[] = {")
        for action in sorted {
            let suffix = symbolSuffix(action)
            lines.append("    {")
            lines.append("        .name = \"\(action.rosName)\",")
            lines.append("        .action_typesupport = action_ts_\(suffix),")
            for role in wrapperRoles {
                lines.append("        .\(role.field)_typesupport = \(role.suffix)_ts_\(suffix),")
                lines.append("        .\(role.field)_create = \(role.suffix)_create_\(suffix),")
                lines.append("        .\(role.field)_destroy = \(role.suffix)_destroy_\(suffix),")
            }
            lines.append("    },")
        }
        lines.append("};")
        lines.append("")
        lines.append("_Static_assert(")
        lines.append(
            "    sizeof(crcl_action_entries) / sizeof(crcl_action_entries[0]) == CRCL_ACTION_REGISTRY_ENTRY_COUNT,"
        )
        lines.append(
            "    \"crcl_action_registry entry count drifted from Generated/crcl_action_registry.h\");")
        lines.append("")
        lines.append("const crcl_action_entry_t *crcl_action_registry_lookup(const char *action_type_name) {")
        lines.append("    if (action_type_name == NULL) {")
        lines.append("        return NULL;")
        lines.append("    }")
        lines.append("    for (size_t i = 0; i < CRCL_ACTION_REGISTRY_ENTRY_COUNT; ++i) {")
        lines.append("        if (strcmp(crcl_action_entries[i].name, action_type_name) == 0) {")
        lines.append("            return &crcl_action_entries[i];")
        lines.append("        }")
        lines.append("    }")
        lines.append("    return NULL;")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    /// Emits `include/Generated/crcl_action_registry.h`: the entry count
    /// consumed by the generated table's `_Static_assert` plus the registered
    /// key list as documentation. The stable API surface (entry struct +
    /// lookup decl) stays in the hand-written `include/crcl_action_registry.h`.
    public static func emitHeader(_ actions: [ActionRef]) -> String {
        let sorted = actions.sorted { $0.rosName < $1.rosName }
        var lines: [String] = []
        lines.append("// Generated by swift-ros2-gen — DO NOT EDIT.")
        lines.append("")
        lines.append("#ifndef CRCL_ACTION_REGISTRY_GENERATED_H")
        lines.append("#define CRCL_ACTION_REGISTRY_GENERATED_H")
        lines.append("")
        lines.append("/// Number of action entries compiled into Generated/crcl_action_registry.c.")
        lines.append("#define CRCL_ACTION_REGISTRY_ENTRY_COUNT \(sorted.count)")
        lines.append("")
        lines.append("// Registered crcl_action_registry_lookup keys:")
        for action in sorted {
            lines.append("//   \(action.rosName)")
        }
        lines.append("")
        lines.append("#endif  // CRCL_ACTION_REGISTRY_GENERATED_H")
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - GetResult splice guard

    /// The action byte seam pins the Result body to CDR offset 4: the
    /// GetResult response frame is `[header (4) | status (1) | pad (3) |
    /// result body]` (`ActionFrameDecoder.encodeGetResultResponse` /
    /// `decodeGetResultResponse`, and the rmw_deserialize splice in
    /// `Sources/CRclBridge/rcl_action_server.c`). Real rosidl CDR pads
    /// `status` to offset 8 when the Result's *first* wire field needs
    /// 8-byte alignment (float64 / int64 / uint64, or a nested struct whose
    /// first field does), so such an action would silently corrupt every
    /// result. Reject it at registry-generation time instead.
    ///
    /// Returns `nil` when the Result's first field is provably 4-byte or
    /// smaller (strings / sequences / bounded strings start with a u32
    /// length, fixed arrays inherit their element's alignment, an empty
    /// rosidl struct contributes a 1-byte dummy). Conservative: anything
    /// that cannot be resolved to a known <=4-byte first field — including
    /// nested references missing from `registry` — is rejected with a
    /// diagnostic citing the splice constraint.
    static func resultSpliceViolation(
        action: ActionRef,
        result: MessageIR,
        registry: [String: MessageIR]
    ) -> String? {
        guard let first = result.fields.first else { return nil }  // empty struct: 1-byte dummy
        guard
            let reason = firstFieldAlignmentViolation(
                of: first.type, registry: registry, depth: 0)
        else { return nil }
        return """
            action '\(action.rosName)': Result's first field '\(first.ros2Name)' \(reason). \
            The action byte seam splices the Result body at fixed CDR offset 4 after \
            [header|status|pad3], but rosidl CDR pads the status to offset 8 before an \
            8-byte-aligned first field, so this action would silently corrupt every \
            GetResult response (see ActionFrameDecoder.encodeGetResultResponse and the \
            rmw_deserialize splice in Sources/CRclBridge/rcl_action_server.c). \
            Reorder the Result so a field with 4-byte-or-smaller alignment comes first.
            """
    }

    /// Returns a human-readable reason when `type`'s leading wire bytes need
    /// 8-byte alignment (or cannot be proven 4-byte-or-smaller), else `nil`.
    private static func firstFieldAlignmentViolation(
        of type: FieldType,
        registry: [String: MessageIR],
        depth: Int
    ) -> String? {
        guard depth < 16 else {
            return "exceeds the nested-type resolution depth, so its alignment cannot be verified"
        }
        switch type {
        case .primitive(let primitive):
            switch primitive {
            case .int64, .uint64, .float64:
                return "is 8-byte aligned (\(primitive.rawValue))"
            case .bool, .byte, .char, .int8, .uint8, .int16, .uint16, .int32, .uint32,
                .float32, .string, .wstring:
                // string / wstring serialize a u32 length first.
                return nil
            }
        case .sequence, .boundedString:
            // u32 count / length comes first.
            return nil
        case .array(let element, _):
            // Fixed arrays have no prefix; alignment is the element's.
            return firstFieldAlignmentViolation(of: element, registry: registry, depth: depth + 1)
        case .nested(let package, let typeName):
            for kind in MessageKind.allCases {
                guard let ir = registry["\(package)/\(kind.rawValue)/\(typeName)"] else { continue }
                guard let nestedFirst = ir.fields.first else { return nil }  // 1-byte dummy
                return firstFieldAlignmentViolation(
                    of: nestedFirst.type, registry: registry, depth: depth + 1)
            }
            return
                "is a nested type ('\(package)/\(typeName)') that cannot be resolved, "
                + "so its alignment cannot be verified"
        }
    }

    // MARK: - per-action emission

    /// The sixteen static wrapper functions for one action: the action
    /// typesupport getter plus (message typesupport + `__create` + `__destroy`)
    /// for each of the five wrapper roles. Wrappers exist so the table stores
    /// uniformly-typed function pointers with defined behavior — assigning
    /// e.g. `<pkg>__action__<Type>_SendGoal_Request__create` (which returns
    /// the concrete struct pointer) to a `void *(*)(void)` slot and calling
    /// through it would be undefined behavior in C.
    private static func wrapperBlock(_ action: ActionRef) -> [String] {
        let pkg = action.package
        let type = action.typeName
        let suffix = symbolSuffix(action)
        var lines: [String] = [
            "// \(action.rosName)",
            "static const rosidl_action_type_support_t *action_ts_\(suffix)(void) {",
            "    return ROSIDL_GET_ACTION_TYPE_SUPPORT(\(pkg), \(type));",
            "}",
        ]
        for role in wrapperRoles {
            let cStruct = "\(pkg)__action__\(type)_\(role.cType)"
            lines.append(contentsOf: [
                "static const rosidl_message_type_support_t *\(role.suffix)_ts_\(suffix)(void) {",
                "    return ROSIDL_GET_MSG_TYPE_SUPPORT(\(pkg), action, \(type)_\(role.cType));",
                "}",
                "static void *\(role.suffix)_create_\(suffix)(void) {",
                "    return \(cStruct)__create();",
                "}",
                "static void \(role.suffix)_destroy_\(suffix)(void *message) {",
                "    \(cStruct)__destroy((\(cStruct) *)message);",
                "}",
            ])
        }
        return lines
    }

    /// Package-qualified wrapper-name suffix, e.g. `example_interfaces__fibonacci`.
    /// The package prefix disambiguates same-named actions across packages.
    private static func symbolSuffix(_ action: ActionRef) -> String {
        "\(action.package)__\(CMarshalEmitter.snakeCase(action.typeName))"
    }

    /// Sorted, de-duplicated rosidl umbrella headers (`<pkg>/action/<snake>.h`)
    /// for the emitted actions. The umbrella pulls in the `__struct`,
    /// `__functions` (create / destroy), and `__type_support` declarations.
    private static func umbrellaIncludes(_ actions: [ActionRef]) -> [String] {
        var seen = Set<String>()
        var headers: [String] = []
        for action in actions {
            let header = "\(action.package)/action/\(CMarshalEmitter.snakeCase(action.typeName)).h"
            if seen.insert(header).inserted {
                headers.append(header)
            }
        }
        return headers.sorted()
    }
}
