/// Emits the per-type native-RCL marshaller C source: a function set that
/// rebuilds a rosidl C message struct from the flat arguments produced by
/// ``MarshalFlattener`` and either publishes it (`crcl_publish_<snake>`) or
/// serializes it (`crcl_serialize_<snake>`). Mirrors the M3a hand-written
/// `crcl_{serialize,publish}_imu` pair, generalized over any ``MessageIR``.
///
/// Task 1 only asserts on the emitted strings — nothing here compiles the
/// generated C. The emitted source references helpers created in Task 3
/// (`crcl_internal.h`, `crcl__set_error`, `crcl__capture_rcl_error`,
/// `crcl_publisher_t`); the emitter merely names them.
public enum CMarshalEmitter {
    public static func emit(_ ir: MessageIR, registry: [String: MessageIR]) -> String {
        let params = MarshalFlattener.flatten(ir, registry: registry)
        let snake = snakeCase(ir.typeName)
        let structC = "\(ir.package)__msg__\(ir.typeName)"
        let paramDecls = params.map(\.cParamDecl).joined(separator: ",\n    ")

        var lines: [String] = []

        lines.append("// Generated by swift-ros2-gen — DO NOT EDIT.")
        lines.append("// Source: \(ir.rosTypeName)")
        lines.append("")
        lines.append("#include \"Generated/crcl_marshal_\(snake).h\"")
        lines.append("")
        lines.append("#include <\(ir.package)/msg/\(snake).h>")
        lines.append("")
        lines.append("#include \"crcl_internal.h\"")
        lines.append("#include <rosidl_runtime_c/string_functions.h>")
        for header in sequenceHeaders(params) {
            lines.append("#include <\(header)>")
        }
        lines.append("#include <rmw/rmw.h>")
        lines.append("#include <rmw/serialized_message.h>")
        lines.append("#include <rcl/publisher.h>")
        lines.append("#include <rcutils/allocator.h>")
        lines.append("#include <rosidl_runtime_c/message_type_support_struct.h>")
        lines.append("#include <string.h>")
        lines.append("#include <stdlib.h>")
        lines.append("#include <stdbool.h>")
        lines.append("")

        // Typesupport accessor.
        lines.append(
            "const rosidl_message_type_support_t *crcl_typesupport_\(snake)(void) {")
        lines.append(
            "    return ROSIDL_GET_MSG_TYPE_SUPPORT(\(ir.package), msg, \(ir.typeName));")
        lines.append("}")
        lines.append("")

        // fill_<snake>: build the rosidl struct from flat args.
        lines.append("static int fill_\(snake)(\(structC) *msg,")
        lines.append("    \(paramDecls)) {")
        lines.append("    memset(msg, 0, sizeof(*msg));")
        for param in params {
            lines.append(contentsOf: fillBody(param).map { "    \($0)" })
        }
        lines.append("    return 1;")
        lines.append("}")
        lines.append("")

        // fini_<snake>: symmetric teardown via the rosidl-generated __fini.
        lines.append("static void fini_\(snake)(\(structC) *msg) {")
        lines.append("    \(structC)__fini(msg);")
        lines.append("}")
        lines.append("")

        // crcl_serialize_<snake>: fill -> rmw_serialize -> copy out.
        lines.append("int crcl_serialize_\(snake)(")
        lines.append("    \(paramDecls),")
        lines.append("    uint8_t **out_buf, size_t *out_len) {")
        lines.append(
            "    const rosidl_message_type_support_t *ts = crcl_typesupport_\(snake)();")
        lines.append("    \(structC) msg;")
        lines.append("    if (!fill_\(snake)(&msg, \(callArgs(params)))) {")
        lines.append("        return -1;  // crcl__set_error already called")
        lines.append("    }")
        lines.append("    rcutils_allocator_t alloc = rcutils_get_default_allocator();")
        lines.append(
            "    rmw_serialized_message_t ser = rmw_get_zero_initialized_serialized_message();")
        lines.append("    rmw_ret_t rc = rmw_serialized_message_init(&ser, 0u, &alloc);")
        lines.append("    if (rc != RMW_RET_OK) {")
        lines.append("        crcl__capture_rcl_error();")
        lines.append("        fini_\(snake)(&msg);")
        lines.append("        return (int)rc;")
        lines.append("    }")
        lines.append("    rc = rmw_serialize(&msg, ts, &ser);")
        lines.append("    if (rc != RMW_RET_OK) {")
        lines.append("        crcl__capture_rcl_error();")
        lines.append("        (void)rmw_serialized_message_fini(&ser);")
        lines.append("        fini_\(snake)(&msg);")
        lines.append("        return (int)rc;")
        lines.append("    }")
        lines.append("    uint8_t *copy = malloc(ser.buffer_length);")
        lines.append("    if (!copy) {")
        lines.append("        crcl__set_error(\"out-of-memory copying serialized message\");")
        lines.append("        (void)rmw_serialized_message_fini(&ser);")
        lines.append("        fini_\(snake)(&msg);")
        lines.append("        return -1;")
        lines.append("    }")
        lines.append("    memcpy(copy, ser.buffer, ser.buffer_length);")
        lines.append("    *out_buf = copy;")
        lines.append("    *out_len = ser.buffer_length;")
        lines.append("    (void)rmw_serialized_message_fini(&ser);")
        lines.append("    fini_\(snake)(&msg);")
        lines.append("    return 0;")
        lines.append("}")
        lines.append("")

        // crcl_publish_<snake>: fill -> rcl_publish -> fini.
        lines.append("int crcl_publish_\(snake)(")
        lines.append("    crcl_publisher_t *pub,")
        lines.append("    \(paramDecls)) {")
        lines.append("    if (!pub) {")
        lines.append("        crcl__set_error(\"crcl_publish_\(snake): null publisher\");")
        lines.append("        return -1;")
        lines.append("    }")
        lines.append("    \(structC) msg;")
        lines.append("    if (!fill_\(snake)(&msg, \(callArgs(params)))) {")
        lines.append("        return -1;  // crcl__set_error already called")
        lines.append("    }")
        lines.append("    rcl_ret_t ret = rcl_publish(&pub->pub, &msg, NULL);")
        lines.append("    fini_\(snake)(&msg);")
        lines.append("    if (ret != RCL_RET_OK) {")
        lines.append("        crcl__capture_rcl_error();")
        lines.append("        return (int)ret;")
        lines.append("    }")
        lines.append("    return 0;")
        lines.append("}")

        return lines.joined(separator: "\n") + "\n"
    }

    /// Emits the per-type public header declaring the three exported symbols
    /// (`crcl_typesupport_<snake>`, `crcl_serialize_<snake>`,
    /// `crcl_publish_<snake>`) with signatures matching ``emit(_:registry:)``.
    /// The aggregator header (`crcl_marshal.h`) `#include`s one of these per
    /// requested type so the decls reach Swift via the `export *` modulemap.
    public static func emitHeader(_ ir: MessageIR, registry: [String: MessageIR]) -> String {
        let params = MarshalFlattener.flatten(ir, registry: registry)
        let snake = snakeCase(ir.typeName)
        let upper = snake.uppercased()
        let paramDecls = params.map(\.cParamDecl).joined(separator: ",\n    ")

        var lines: [String] = []
        lines.append("// Generated by swift-ros2-gen — DO NOT EDIT.")
        lines.append("// Source: \(ir.rosTypeName)")
        lines.append("")
        lines.append("#ifndef CRCL_MARSHAL_\(upper)_H")
        lines.append("#define CRCL_MARSHAL_\(upper)_H")
        lines.append("")
        lines.append("#include <stddef.h>")
        lines.append("#include <stdint.h>")
        lines.append("#include <rosidl_runtime_c/message_type_support_struct.h>")
        lines.append("")
        lines.append("#ifdef __cplusplus")
        lines.append("extern \"C\" {")
        lines.append("#endif")
        lines.append("")
        // Forward-declare the publisher handle as an incomplete type so this
        // header (which reaches Swift through the modulemap) never exposes the
        // struct body — that body lives in crcl_internal.h, included only by the
        // generated .c. Repeating the identical typedef is legal in C11.
        lines.append("typedef struct crcl_publisher_s crcl_publisher_t;")
        lines.append("")
        // Typesupport accessor.
        lines.append("const rosidl_message_type_support_t *crcl_typesupport_\(snake)(void);")
        lines.append("")
        // crcl_serialize_<snake>.
        lines.append("int crcl_serialize_\(snake)(")
        lines.append("    \(paramDecls),")
        lines.append("    uint8_t **out_buf, size_t *out_len);")
        lines.append("")
        // crcl_publish_<snake>.
        lines.append("int crcl_publish_\(snake)(")
        lines.append("    crcl_publisher_t *pub,")
        lines.append("    \(paramDecls));")
        lines.append("")
        lines.append("#ifdef __cplusplus")
        lines.append("}")
        lines.append("#endif")
        lines.append("#endif  // CRCL_MARSHAL_\(upper)_H")

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - fill body per param

    private static func fillBody(_ param: FlatParam) -> [String] {
        switch param.kind {
        case .scalar:
            return assignScalar(lvalue: param.cStructPath, rvalue: param.paramName, indent: "")

        case .heapString:
            return assignString(
                lvalue: param.cStructPath, rvalue: param.paramName, errorName: param.paramName, indent: "")

        case .fixedArray(let elementC, let length):
            return [
                "memcpy(\(param.cStructPath), \(param.paramName), "
                    + "\(length) * sizeof(\(elementC)));"
            ]

        case .scalarSequence(let elementC):
            let seqInit = sequenceInit(forC: elementC)
            return [
                "if (!\(seqInit)(&\(param.cStructPath), \(param.paramName)_count)) {",
                "    crcl__set_error(\"\(param.paramName) sequence init failed\");",
                "    return 0;",
                "}",
                "if (\(param.paramName)_count) {",
                "    memcpy(\(param.cStructPath).data, \(param.paramName)_data, "
                    + "\(param.paramName)_count * sizeof(\(elementC)));",
                "}",
            ]

        case .structSequence(let elementType, let members):
            let prefix = param.paramName
            var body: [String] = []
            body.append("if (!\(elementType)__Sequence__init(&\(param.cStructPath), \(prefix)_len)) {")
            body.append("    crcl__set_error(\"\(prefix) sequence init failed\");")
            body.append("    return 0;")
            body.append("}")
            body.append("for (size_t i = 0; i < \(prefix)_len; ++i) {")
            for member in members {
                let target = "\(param.cStructPath).data[i]\(member.cStructPath)"
                switch member.kind {
                case .heapString:
                    body.append(
                        contentsOf: assignString(
                            lvalue: target, rvalue: "\(member.paramName)[i]",
                            errorName: member.paramName, indent: "    "))
                case .scalar:
                    body.append(
                        contentsOf: assignScalar(
                            lvalue: target, rvalue: "\(member.paramName)[i]", indent: "    "))
                default:
                    preconditionFailure(
                        "CMarshalEmitter: unsupported struct-sequence member kind for \(member.paramName)")
                }
            }
            body.append("}")
            return body
        }
    }

    /// Emits `<lvalue> = <rvalue>;`, prefixed by `indent`.
    private static func assignScalar(lvalue: String, rvalue: String, indent: String) -> [String] {
        ["\(indent)\(lvalue) = \(rvalue);"]
    }

    /// Emits the `rosidl_runtime_c__String__assign` guard that fills `lvalue`
    /// from `rvalue` (NULL-coalesced to `""`), failing with `errorName` in the
    /// diagnostic. Every line is prefixed by `indent`.
    private static func assignString(
        lvalue: String, rvalue: String, errorName: String, indent: String
    ) -> [String] {
        [
            "\(indent)if (!rosidl_runtime_c__String__assign(&\(lvalue), "
                + "\(rvalue) ? \(rvalue) : \"\")) {",
            "\(indent)    crcl__set_error(\"String__assign failed for \(errorName)\");",
            "\(indent)    return 0;",
            "\(indent)}",
        ]
    }

    /// Comma-joined call-site argument names for `fill_<snake>`. Scalar
    /// sequences expand to `<p>_data, <p>_count`; struct sequences to each
    /// member's array plus `<p>_len`; everything else is the bare param name.
    private static func callArgs(_ params: [FlatParam]) -> String {
        var args: [String] = []
        for param in params {
            switch param.kind {
            case .scalar, .heapString, .fixedArray:
                args.append(param.paramName)
            case .scalarSequence:
                args.append("\(param.paramName)_data")
                args.append("\(param.paramName)_count")
            case .structSequence(_, let members):
                for member in members { args.append(member.paramName) }
                args.append("\(param.paramName)_len")
            }
        }
        return args.joined(separator: ", ")
    }

    // MARK: - sequence helpers

    /// rosidl primitive-sequence init function for a C element type, e.g.
    /// `uint8_t` -> `rosidl_runtime_c__uint8__Sequence__init`. The rosidl
    /// "cname" set is `{boolean, char, octet, int8, uint8, int16, uint16,
    /// int32, uint32, int64, uint64, float, double, wchar}` (see
    /// `rosidl_runtime_c/primitives_sequence_functions.h`).
    private static func sequenceInit(forC cType: String) -> String {
        "rosidl_runtime_c__\(sequenceCName(forC: cType))__Sequence__init"
    }

    private static func sequenceCName(forC cType: String) -> String {
        switch cType {
        case "bool": return "boolean"
        case "uint8_t": return "uint8"
        case "int8_t": return "int8"
        case "int16_t": return "int16"
        case "uint16_t": return "uint16"
        case "int32_t": return "int32"
        case "uint32_t": return "uint32"
        case "int64_t": return "int64"
        case "uint64_t": return "uint64"
        case "float": return "float"
        case "double": return "double"
        default:
            // Unreachable backstop: the flattener only produces the enumerated
            // primitive C types above.
            preconditionFailure("CMarshalEmitter: no rosidl sequence cname for C type \(cType)")
        }
    }

    /// Extra includes needed for the sequence init functions used by `params`.
    /// Primitive sequences come from `primitives_sequence_functions.h`; struct
    /// sequences come from the element type's own `<pkg>/msg/<snake>.h` umbrella.
    private static func sequenceHeaders(_ params: [FlatParam]) -> [String] {
        var headers: [String] = []
        var seen = Set<String>()
        func add(_ h: String) {
            if seen.insert(h).inserted { headers.append(h) }
        }
        for param in params {
            switch param.kind {
            case .scalarSequence:
                add("rosidl_runtime_c/primitives_sequence_functions.h")
            case .structSequence(let elementType, _):
                // elementType is "<pkg>__msg__<Type>" — derive the umbrella header.
                let parts = elementType.components(separatedBy: "__msg__")
                if parts.count == 2 {
                    add("\(parts[0])/msg/\(snakeCase(parts[1])).h")
                }
            default:
                break
            }
        }
        return headers
    }

    // MARK: - naming

    /// PascalCase / acronym-aware snake_case, matching rosidl's file naming:
    /// `PointCloud2` -> `point_cloud2`, `CompressedImage` -> `compressed_image`,
    /// `BatteryState` -> `battery_state`, `Imu` -> `imu`.
    static func snakeCase(_ pascal: String) -> String {
        var out = ""
        let chars = Array(pascal)
        for (i, ch) in chars.enumerated() {
            if ch.isUppercase {
                let prev = i > 0 ? chars[i - 1] : nil
                if let prev, !prev.isUppercase {
                    out.append("_")
                }
                out.append(Character(ch.lowercased()))
            } else {
                out.append(ch)
            }
        }
        return out
    }
}
