/// Emits the generated RCL *service* typesupport registry
/// (`Generated/crcl_srv_registry.c` + `include/Generated/crcl_srv_registry.h`).
///
/// Per the M7 serialize-shim design, the generator emits no per-field service
/// marshalling — only a registry: per `.srv` type, getters for the service
/// typesupport (`ROSIDL_GET_SRV_TYPE_SUPPORT`), the request / response
/// *message* typesupports (`ROSIDL_GET_MSG_TYPE_SUPPORT` with the `srv`
/// subfolder), and the rosidl `__create` / `__destroy` pairs for both halves.
/// The entry struct (`crcl_srv_entry_t`) and the lookup declaration live in
/// the hand-written `Sources/CRclBridge/include/crcl_srv_registry.h`; the
/// generated file only fills the table and implements the lookup.
public enum CSrvRegistryEmitter {
    /// Identifies one `.srv` type to register. Sorting / lookup key is the
    /// canonical ROS service name `"<package>/srv/<TypeName>"`.
    public struct ServiceRef: Equatable, Sendable {
        public let package: String
        public let typeName: String

        public init(package: String, typeName: String) {
            self.package = package
            self.typeName = typeName
        }

        public var rosName: String { "\(package)/srv/\(typeName)" }
    }

    /// Emits `crcl_srv_registry.c`. Entries are sorted by canonical ROS name
    /// for deterministic regeneration.
    public static func emit(_ services: [ServiceRef]) -> String {
        let sorted = services.sorted { $0.rosName < $1.rosName }
        var lines: [String] = []
        lines.append("// Generated by swift-ros2-gen — DO NOT EDIT.")
        lines.append("")
        lines.append("#include \"Generated/crcl_srv_registry.h\"")
        lines.append("")
        lines.append("#include \"crcl_srv_registry.h\"")
        lines.append("")
        for include in umbrellaIncludes(sorted) {
            lines.append("#include <\(include)>")
        }
        lines.append("#include <rosidl_runtime_c/message_type_support_struct.h>")
        lines.append("#include <rosidl_runtime_c/service_type_support_struct.h>")
        lines.append("#include <stddef.h>")
        lines.append("#include <string.h>")
        lines.append("")
        for service in sorted {
            lines.append(contentsOf: wrapperBlock(service))
            lines.append("")
        }
        lines.append("static const crcl_srv_entry_t crcl_srv_entries[] = {")
        for service in sorted {
            let suffix = symbolSuffix(service)
            lines.append("    {")
            lines.append("        .name = \"\(service.rosName)\",")
            lines.append("        .service_typesupport = srv_ts_\(suffix),")
            lines.append("        .request_typesupport = req_ts_\(suffix),")
            lines.append("        .response_typesupport = res_ts_\(suffix),")
            lines.append("        .request_create = req_create_\(suffix),")
            lines.append("        .request_destroy = req_destroy_\(suffix),")
            lines.append("        .response_create = res_create_\(suffix),")
            lines.append("        .response_destroy = res_destroy_\(suffix),")
            lines.append("    },")
        }
        lines.append("};")
        lines.append("")
        lines.append("_Static_assert(")
        lines.append(
            "    sizeof(crcl_srv_entries) / sizeof(crcl_srv_entries[0]) == CRCL_SRV_REGISTRY_ENTRY_COUNT,")
        lines.append("    \"crcl_srv_registry entry count drifted from Generated/crcl_srv_registry.h\");")
        lines.append("")
        lines.append("const crcl_srv_entry_t *crcl_srv_registry_lookup(const char *srv_type_name) {")
        lines.append("    if (srv_type_name == NULL) {")
        lines.append("        return NULL;")
        lines.append("    }")
        lines.append("    for (size_t i = 0; i < CRCL_SRV_REGISTRY_ENTRY_COUNT; ++i) {")
        lines.append("        if (strcmp(crcl_srv_entries[i].name, srv_type_name) == 0) {")
        lines.append("            return &crcl_srv_entries[i];")
        lines.append("        }")
        lines.append("    }")
        lines.append("    return NULL;")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    /// Emits `include/Generated/crcl_srv_registry.h`: the entry count consumed
    /// by the generated table's `_Static_assert` plus the registered key list
    /// as documentation. The stable API surface (entry struct + lookup decl)
    /// stays in the hand-written `include/crcl_srv_registry.h`.
    public static func emitHeader(_ services: [ServiceRef]) -> String {
        let sorted = services.sorted { $0.rosName < $1.rosName }
        var lines: [String] = []
        lines.append("// Generated by swift-ros2-gen — DO NOT EDIT.")
        lines.append("")
        lines.append("#ifndef CRCL_SRV_REGISTRY_GENERATED_H")
        lines.append("#define CRCL_SRV_REGISTRY_GENERATED_H")
        lines.append("")
        lines.append("/// Number of service entries compiled into Generated/crcl_srv_registry.c.")
        lines.append("#define CRCL_SRV_REGISTRY_ENTRY_COUNT \(sorted.count)")
        lines.append("")
        lines.append("// Registered crcl_srv_registry_lookup keys:")
        for service in sorted {
            lines.append("//   \(service.rosName)")
        }
        lines.append("")
        lines.append("#endif  // CRCL_SRV_REGISTRY_GENERATED_H")
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - per-service emission

    /// The seven static wrapper functions for one service. Wrappers exist so
    /// the table stores uniformly-typed function pointers with defined
    /// behavior — assigning e.g. `<pkg>__srv__<Type>_Request__create` (which
    /// returns the concrete struct pointer) to a `void *(*)(void)` slot and
    /// calling through it would be undefined behavior in C.
    private static func wrapperBlock(_ service: ServiceRef) -> [String] {
        let pkg = service.package
        let type = service.typeName
        let suffix = symbolSuffix(service)
        let request = "\(pkg)__srv__\(type)_Request"
        let response = "\(pkg)__srv__\(type)_Response"
        return [
            "// \(service.rosName)",
            "static const rosidl_service_type_support_t *srv_ts_\(suffix)(void) {",
            "    return ROSIDL_GET_SRV_TYPE_SUPPORT(\(pkg), srv, \(type));",
            "}",
            "static const rosidl_message_type_support_t *req_ts_\(suffix)(void) {",
            "    return ROSIDL_GET_MSG_TYPE_SUPPORT(\(pkg), srv, \(type)_Request);",
            "}",
            "static const rosidl_message_type_support_t *res_ts_\(suffix)(void) {",
            "    return ROSIDL_GET_MSG_TYPE_SUPPORT(\(pkg), srv, \(type)_Response);",
            "}",
            "static void *req_create_\(suffix)(void) {",
            "    return \(request)__create();",
            "}",
            "static void req_destroy_\(suffix)(void *request) {",
            "    \(request)__destroy((\(request) *)request);",
            "}",
            "static void *res_create_\(suffix)(void) {",
            "    return \(response)__create();",
            "}",
            "static void res_destroy_\(suffix)(void *response) {",
            "    \(response)__destroy((\(response) *)response);",
            "}",
        ]
    }

    /// Package-qualified wrapper-name suffix, e.g. `std_srvs__set_bool`. The
    /// package prefix disambiguates same-named services across packages
    /// (`std_srvs/Trigger` vs `example_interfaces/Trigger`).
    private static func symbolSuffix(_ service: ServiceRef) -> String {
        "\(service.package)__\(CMarshalEmitter.snakeCase(service.typeName))"
    }

    /// Sorted, de-duplicated rosidl umbrella headers (`<pkg>/srv/<snake>.h`)
    /// for the emitted services. The umbrella pulls in the `__struct`,
    /// `__functions` (create / destroy), and `__type_support` declarations.
    private static func umbrellaIncludes(_ services: [ServiceRef]) -> [String] {
        var seen = Set<String>()
        var headers: [String] = []
        for service in services {
            let header = "\(service.package)/srv/\(CMarshalEmitter.snakeCase(service.typeName)).h"
            if seen.insert(header).inserted {
                headers.append(header)
            }
        }
        return headers.sorted()
    }
}
