/// Emits the per-type native-RCL Swift "unpacker" source: the gated bridge that
/// destructures a Swift message value into the *same* flat arguments the C
/// marshaller (``CMarshalEmitter``) expects, then calls the per-type C
/// functions. For one ``MessageIR`` it produces two things, mirroring the M3a
/// hand-written `RclImuMarshal.swift`:
///
/// 1. `package func rclSerialize<Struct>(_ value: <Struct>) throws -> [UInt8]`
///    — fills via `crcl_serialize_<snake>` (validation / serialization path).
/// 2. `extension <Struct>: RclTypedPublishable { rclTypedPublish(into:) }`
///    — fills via `crcl_publish_<snake>` (production publish path).
///
/// Both functions destructure the value into flat C call arguments using the
/// exact ordering ``MarshalFlattener/flatten(_:registry:)`` produces, so the
/// Swift call site and the emitted C signature agree argument-for-argument.
///
/// Task 2 only asserts on the emitted strings — nothing here compiles. The
/// emitted source references symbols that exist in the `SwiftROS2RCL` module
/// (`RclPublisherBox`, `RclPublisherHandle`, `RclTypedPublishable`,
/// `TransportError`, and the `crcl_*` FFI from `CRclBridge`).
public enum RclMarshalSwiftEmitter {
    public static func emit(_ ir: MessageIR, registry: [String: MessageIR]) -> String {
        let params = MarshalFlattener.flatten(ir, registry: registry)
        let structName = SwiftEmitter.swiftStructName(typeName: ir.typeName)
        let snake = CMarshalEmitter.snakeCase(ir.typeName)
        let needsCStringHelper = params.contains { param in
            if case .structSequence(_, let members) = param.kind {
                return members.contains { if case .heapString = $0.kind { return true } else { return false } }
            }
            return false
        }

        var out = ""
        out += "// Generated by swift-ros2-gen \u{2014} DO NOT EDIT.\n"
        out += "// Source: \(ir.rosTypeName)\n"
        out += "\n"
        out += "import CRclBridge\n"
        out += "import Foundation\n"
        out += "import SwiftROS2Messages\n"
        out += "import SwiftROS2Transport\n"
        out += "\n"

        if needsCStringHelper {
            out += cStringArrayHelper()
            out += "\n"
        }

        // 1. rclSerialize<Struct>: value-rooted, calls crcl_serialize_<snake>.
        out += "/// Serialize `value` via the real ROS 2 introspection serializer\n"
        out += "/// (rmw_serialize), returning the on-wire CDR bytes (incl. the 4-byte\n"
        out += "/// encapsulation header).\n"
        out += "package func rclSerialize\(structName)(_ value: \(structName)) throws -> [UInt8] {\n"
        out += "    var outBuf: UnsafeMutablePointer<UInt8>?\n"
        out += "    var outLen: Int = 0\n"
        out += renderCall(
            params: params,
            valueRoot: "value.",
            resultDecl: "    let rc: Int32 =",
            innerExprPrefix: "crcl_serialize_\(snake)(",
            innerExprSuffix: ", &outBuf, &outLen)",
            baseIndent: "    ")
        out += "    guard rc == 0, let outBuf else {\n"
        out += "        throw TransportError.publishFailed(String(cString: crcl_last_error()))\n"
        out += "    }\n"
        out += "    defer { crcl_free(outBuf) }\n"
        out += "    return Array(UnsafeBufferPointer(start: outBuf, count: outLen))\n"
        out += "}\n"
        out += "\n"

        // 2. extension <Struct>: RclTypedPublishable — calls crcl_publish_<snake>.
        out += "extension \(structName): RclTypedPublishable {\n"
        out += "    /// Marshal this \(structName) into its rosidl C struct and publish\n"
        out += "    /// via rcl_publish (crcl_publish_\(snake)).\n"
        out += "    package func rclTypedPublish(into handle: any RclPublisherHandle) throws {\n"
        out += "        guard let box = handle as? RclPublisherBox else {\n"
        out += "            throw TransportError.publishFailed(\n"
        out += "                \"rclTypedPublish: unexpected publisher handle type\")\n"
        out += "        }\n"
        out += renderCall(
            params: params,
            valueRoot: "",
            resultDecl: "        let rc: Int32? =",
            innerExprPrefix: "crcl_publish_\(snake)(",
            innerExprSuffix: ")",
            baseIndent: "        ",
            innerOpener: "box.withPtr { p in",
            firstCallArg: "p")
        out += "        guard let rc else { throw TransportError.publisherClosed }\n"
        out += "        if rc != 0 { throw TransportError.publishFailed(String(cString: crcl_last_error())) }\n"
        out += "    }\n"
        out += "}\n"

        return out
    }

    // MARK: - call rendering

    /// Render the nested-closure block for one C call. `valueRoot` is prepended
    /// to each param's `swiftValuePath` (`"value."` for the serialize free
    /// function; `""` — unqualified `self`-relative — inside the extension).
    /// `resultDecl` is the assignment LHS (e.g. `let rc: Int32 =`). The innermost
    /// expression is `innerExprPrefix + <comma-joined call args> + innerExprSuffix`.
    private static func renderCall(
        params: [FlatParam],
        valueRoot: String,
        resultDecl: String,
        innerExprPrefix: String,
        innerExprSuffix: String,
        baseIndent: String,
        innerOpener: String? = nil,
        firstCallArg: String? = nil
    ) -> String {
        var setup: [String] = []  // struct-sequence parallel-array `let` bindings
        var openers: [String] = []  // closure-opening lines, outer → inner
        var callArgs: [String] = []  // C call arguments, in flat-param order
        if let firstCallArg { callArgs.append(firstCallArg) }

        for param in params {
            let path = valueRoot + param.swiftValuePath
            switch param.kind {
            case .scalar, .heapString:
                callArgs.append(path)

            case .fixedArray(_, let length):
                // Guard the fixed-length contract before handing C a base
                // pointer it will memcpy `length` elements from — a short Swift
                // array would otherwise read out of bounds.
                setup.append(
                    "precondition(\(path).count == \(length), \"\(param.paramName) needs \(length) elements\")")
                let buf = "\(swiftLocal(param.paramName))Buf"
                openers.append("\(path).withUnsafeBufferPointer { \(buf) in")
                callArgs.append("\(buf).baseAddress")

            case .scalarSequence:
                let buf = "\(swiftLocal(param.paramName))Buf"
                openers.append("\(path).withUnsafeBufferPointer { \(buf) in")
                callArgs.append("\(buf).baseAddress")
                callArgs.append("\(buf).count")

            case .structSequence(_, let members):
                // Struct-of-arrays: one parallel Swift array per member, then a
                // withUnsafeBufferPointer (scalar) or withCStringArray (string)
                // per member to hand C a contiguous pointer.
                for member in members {
                    let arrName = "\(swiftLocal(member.paramName))Array"
                    setup.append("let \(arrName) = \(path).map { $0.\(member.swiftValuePath) }")
                    switch member.kind {
                    case .heapString:
                        let ptr = "\(swiftLocal(member.paramName))Ptr"
                        openers.append("withCStringArray(\(arrName)) { \(ptr) in")
                        callArgs.append(ptr)
                    case .scalar:
                        let buf = "\(swiftLocal(member.paramName))Buf"
                        openers.append("\(arrName).withUnsafeBufferPointer { \(buf) in")
                        callArgs.append("\(buf).baseAddress")
                    default:
                        preconditionFailure(
                            "RclMarshalSwiftEmitter: unsupported struct-sequence member kind "
                                + "for \(member.paramName)")
                    }
                }
                callArgs.append("\(path).count")
            }
        }

        // Append the caller-supplied innermost opener (e.g. `box.withPtr { p in`)
        // last so it nests deepest; its closing brace is emitted alongside the
        // value-derived closures below.
        if let innerOpener { openers.append(innerOpener) }

        var lines: [String] = []
        for line in setup {
            lines.append("\(baseIndent)\(line)")
        }

        // Compose the nested closures. The inner expression depth grows by 4
        // spaces per opener (matching the hand-written RclImuMarshal style).
        // `resultDecl` already carries its own indentation (it is the
        // assignment LHS at `baseIndent`). The closure bodies indent one extra
        // level per opener relative to `baseIndent`. The C call's arguments are
        // emitted one-per-line so the generated source stays within the
        // 120-column lint limit regardless of how many flat params a message
        // expands to.
        if openers.isEmpty {
            lines.append(
                contentsOf: callExprLines(
                    resultDecl + " " + innerExprPrefix, callArgs, innerExprSuffix, baseIndent))
        } else {
            lines.append(resultDecl)
            for (i, opener) in openers.enumerated() {
                lines.append("\(baseIndent)\(indent(i + 1))\(opener)")
            }
            lines.append(
                contentsOf: callExprLines(
                    innerExprPrefix, callArgs, innerExprSuffix,
                    baseIndent + indent(openers.count + 1)))
            for i in stride(from: openers.count, through: 1, by: -1) {
                lines.append("\(baseIndent)\(indent(i))}")
            }
        }
        return lines.map { $0 + "\n" }.joined()
    }

    /// Render a C call with one argument per line, each indented one level past
    /// `indentBase`. `prefix` is the opening text (function name + `(`, possibly
    /// preceded by a result-decl / closure opener); `suffix` is the closing
    /// text after the final argument (the `)` plus any trailing fixed args /
    /// closure brace). Keeping the call multi-line keeps the generated source
    /// under the 120-column lint limit regardless of param count.
    private static func callExprLines(
        _ prefix: String, _ args: [String], _ suffix: String, _ indentBase: String
    ) -> [String] {
        var out: [String] = []
        out.append("\(indentBase)\(prefix)")
        for (i, arg) in args.enumerated() {
            let trailer = i == args.count - 1 ? suffix : ","
            out.append("\(indentBase)\(indent(1))\(arg)\(trailer)")
        }
        return out
    }

    private static func indent(_ depth: Int) -> String {
        String(repeating: "    ", count: depth)
    }

    /// Convert a snake_case flat-param name into a lowerCamelCase Swift local
    /// identifier (e.g. `orientation_covariance` → `orientationCovariance`),
    /// satisfying swift-format's `AlwaysUseLowerCamelCase` rule. C call sites
    /// keep the snake-case argument *values* — only the Swift-side binding names
    /// change.
    private static func swiftLocal(_ snake: String) -> String {
        let parts = snake.split(separator: "_")
        guard let first = parts.first else { return snake }
        return ([String(first)] + parts.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() })
            .joined()
    }

    /// The fileprivate `withCStringArray` helper. Builds a contiguous
    /// `[UnsafePointer<CChar>?]` keeping each `withCString` alive via recursion,
    /// then hands C the base address. Emitted once per file, only when a
    /// struct-sequence has a string member (e.g. `PointField.name`).
    private static func cStringArrayHelper() -> String {
        """
        private func withCStringArray<R>(
            _ strings: [String], _ body: (UnsafePointer<UnsafePointer<CChar>?>) throws -> R
        ) rethrows -> R {
            func recurse(_ i: Int, _ acc: inout [UnsafePointer<CChar>?]) throws -> R {
                if i == strings.count {
                    return try acc.withUnsafeBufferPointer { try body($0.baseAddress!) }
                }
                return try strings[i].withCString { cs in
                    acc.append(cs)
                    return try recurse(i + 1, &acc)
                }
            }
            var acc: [UnsafePointer<CChar>?] = []
            acc.reserveCapacity(strings.count)
            return try recurse(0, &acc)
        }

        """
    }
}
