/// Converts a ``MessageIR`` into the Swift source text for a generated ``ROS2Message`` type.
public enum SwiftEmitter {
    /// Type names that collide with Swift stdlib types — these keep the `Msg` suffix so the
    /// generated symbol does not shadow the stdlib one. Anything else emits as bare PascalCase.
    private static let collisionTypeNames: Set<String> = [
        "Bool", "String",
        "Int", "Int8", "Int16", "Int32", "Int64",
        "UInt", "UInt8", "UInt16", "UInt32", "UInt64",
        "Float", "Float32", "Float64", "Double",
        "Empty",
    ]

    public static func emit(_ ir: MessageIR, sourceLabel: String) -> String {
        var out = ""
        out += "// Generated by swift-ros2-gen \u{2014} DO NOT EDIT.\n"
        out += "// Source: \(sourceLabel)\n"
        out += "\n"
        out += "import SwiftROS2CDR\n"
        out += "\n"
        out += "/// \(ir.rosTypeName)\n"
        let structName = swiftStructName(typeName: ir.typeName)
        out += "public struct \(structName): ROS2Message, Equatable, Sendable {\n"
        guard let hash = ir.perDistroHashes["jazzy"] else {
            preconditionFailure("MessageIR for \(ir.rosTypeName) is missing the 'jazzy' type hash")
        }
        out += "    public static let typeInfo = ROS2MessageTypeInfo(\n"
        out += "        typeName: \"\(ir.rosTypeName)\",\n"
        out += "        typeHash: \"\(hash)\"\n"
        out += "    )\n"
        out += "\n"
        if ir.fields.isEmpty {
            out += "    public init() {}\n"
            out += "\n"
            out += "    public func encode(to encoder: CDREncoder) throws {}\n"
            out += "\n"
            out += "    public init(from decoder: CDRDecoder) throws {}\n"
        } else {
            for field in ir.fields {
                out += "    public var \(field.swiftName): \(swiftType(field.type))\n"
            }
            out += "\n"
            if ir.fields.count == 1, let field = ir.fields.first {
                out += "    public init(\(field.swiftName): \(swiftType(field.type)) = \(swiftDefault(field.type))) {\n"
                out += "        self.\(field.swiftName) = \(field.swiftName)\n"
            } else {
                out += "    public init(\n"
                for (i, field) in ir.fields.enumerated() {
                    let comma = i == ir.fields.count - 1 ? "" : ","
                    let typeName = swiftType(field.type)
                    let defaultVal = swiftDefault(field.type)
                    out += "        \(field.swiftName): \(typeName) = \(defaultVal)\(comma)\n"
                }
                out += "    ) {\n"
                for field in ir.fields {
                    out += "        self.\(field.swiftName) = \(field.swiftName)\n"
                }
            }
            out += "    }\n"
            out += "\n"
            out += "    public func encode(to encoder: CDREncoder) throws {\n"
            for field in ir.fields {
                out += emitEncodeStatement(field) + "\n"
            }
            out += "    }\n"
            out += "\n"
            out += "    public init(from decoder: CDRDecoder) throws {\n"
            for field in ir.fields {
                out += emitDecodeStatement(field) + "\n"
            }
            out += "    }\n"
        }
        out += "}\n"
        return out
    }

    /// Convention: append `Msg` only when the type name collides with a Swift stdlib name
    /// (or `Empty`, kept for ROS-conventional symmetry with Phase 1). Anything else emits
    /// as bare PascalCase. All generated types coexist in the `SwiftROS2Messages` Swift
    /// module so the bare name is unambiguous.
    public static func swiftStructName(typeName: String) -> String {
        collisionTypeNames.contains(typeName) ? typeName + "Msg" : typeName
    }

    static func swiftType(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p): return p.swiftTypeName
        case .nested(_, let typeName):
            return swiftStructName(typeName: typeName)
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter.swiftType: array/sequence/boundedString not yet implemented (Phase 3 Task 9)")
        }
    }

    static func swiftDefault(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "false"
            case .byte, .uint8, .char, .int8,
                .int16, .uint16, .int32, .uint32, .int64, .uint64:
                return "0"
            case .float32, .float64: return "0.0"
            case .string, .wstring: return "\"\""
            }
        case .nested(_, let typeName):
            return "\(swiftStructName(typeName: typeName))()"
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter.swiftDefault: array/sequence/boundedString not yet implemented (Phase 3 Task 9)")
        }
    }

    static func emitEncodeStatement(_ field: FieldIR) -> String {
        switch field.type {
        case .primitive:
            return "        encoder.\(writerCall(field.type))(\(field.swiftName))"
        case .nested:
            return "        try \(field.swiftName).encode(to: encoder)"
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter.emitEncodeStatement: array/sequence/boundedString not yet implemented (Phase 3 Task 9)")
        }
    }

    static func emitDecodeStatement(_ field: FieldIR) -> String {
        switch field.type {
        case .primitive:
            return "        self.\(field.swiftName) = try decoder.\(readerCall(field.type))()"
        case .nested(_, let typeName):
            return "        self.\(field.swiftName) = try \(swiftStructName(typeName: typeName))(from: decoder)"
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter.emitDecodeStatement: array/sequence/boundedString not yet implemented (Phase 3 Task 9)")
        }
    }

    static func writerCall(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "writeBool"
            case .byte, .uint8: return "writeUInt8"
            case .char, .int8: return "writeInt8"
            case .int16: return "writeInt16"
            case .uint16: return "writeUInt16"
            case .int32: return "writeInt32"
            case .uint32: return "writeUInt32"
            case .int64: return "writeInt64"
            case .uint64: return "writeUInt64"
            case .float32: return "writeFloat32"
            case .float64: return "writeFloat64"
            case .string, .wstring: return "writeString"
            }
        case .nested:
            preconditionFailure("writerCall is not defined for nested types — use emitEncodeStatement")
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter.writerCall: array/sequence/boundedString not yet implemented (Phase 3 Task 9)")
        }
    }

    static func readerCall(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "readBool"
            case .byte, .uint8: return "readUInt8"
            case .char, .int8: return "readInt8"
            case .int16: return "readInt16"
            case .uint16: return "readUInt16"
            case .int32: return "readInt32"
            case .uint32: return "readUInt32"
            case .int64: return "readInt64"
            case .uint64: return "readUInt64"
            case .float32: return "readFloat32"
            case .float64: return "readFloat64"
            case .string, .wstring: return "readString"
            }
        case .nested:
            preconditionFailure("readerCall is not defined for nested types — use emitDecodeStatement")
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter.readerCall: array/sequence/boundedString not yet implemented (Phase 3 Task 9)")
        }
    }
}
