/// Converts a ``MessageIR`` into the Swift source text for a generated ``ROS2Message`` type.
public enum SwiftEmitter {
    /// Type names that collide with Swift stdlib types — these keep the `Msg` suffix so the
    /// generated symbol does not shadow the stdlib one. Anything else emits as bare PascalCase.
    private static let collisionTypeNames: Set<String> = [
        "Bool", "String",
        "Int", "Int8", "Int16", "Int32", "Int64",
        "UInt", "UInt8", "UInt16", "UInt32", "UInt64",
        "Float", "Float32", "Float64", "Double",
        "Empty",
    ]

    /// Render `ir` to Swift source.
    ///
    /// - Parameters:
    ///   - isNested: when `true`, drop `ROS2Message` conformance + the `typeInfo` constant.
    ///     Used for nested-only payloads (e.g. `Header`, `Vector3`, `UUID`) that must not be
    ///     advertised as a top-level topic.
    ///   - structNameOverride: when non-nil, overrides the default
    ///     ``swiftStructName(typeName:)`` mapping. Used to prefix cross-package collisions like
    ///     `unique_identifier_msgs/UUID` → `UniqueIdentifierUUID`.
    ///   - nestedNameOverrides: per-reference Swift-name overrides keyed by
    ///     `<package>/msg/<TypeName>`. When a nested field's full ROS name is in the map, the
    ///     mapped value wins over ``swiftStructName(typeName:)``.
    public static func emit(
        _ ir: MessageIR,
        sourceLabel: String,
        isNested: Bool = false,
        structNameOverride: String? = nil,
        nestedNameOverrides: [String: String] = [:]
    ) -> String {
        var out = ""
        out += "// Generated by swift-ros2-gen \u{2014} DO NOT EDIT.\n"
        out += "// Source: \(sourceLabel)\n"
        out += "\n"
        out += "import SwiftROS2CDR\n"
        out += "\n"
        out += "/// \(ir.rosTypeName)\n"
        let structName = structNameOverride ?? swiftStructName(typeName: ir.typeName)
        let conformance = isNested ? "CDRCodable, Equatable, Sendable" : "ROS2Message, Equatable, Sendable"
        out += "public struct \(structName): \(conformance) {\n"

        var preludeEmitted = false
        if !isNested {
            guard let hash = ir.perDistroHashes["jazzy"] else {
                preconditionFailure("MessageIR for \(ir.rosTypeName) is missing the 'jazzy' type hash")
            }
            out += "    public static let typeInfo = ROS2MessageTypeInfo(\n"
            out += "        typeName: \"\(ir.rosTypeName)\",\n"
            out += "        typeHash: \"\(hash)\"\n"
            out += "    )\n"
            preludeEmitted = true
        }

        if !ir.constants.isEmpty {
            if preludeEmitted {
                out += "\n"
            }
            for c in ir.constants {
                // ROS constants are conventionally UPPER_SNAKE; opt out of swift-format's
                // lowerCamelCase rule per-line so generated files lint cleanly.
                out += "    // swift-format-ignore: AlwaysUseLowerCamelCase\n"
                out += "    public static let \(c.swiftName): "
                out += "\(c.type.swiftTypeName) = \(swiftLiteral(c.value))\n"
            }
            preludeEmitted = true
        }

        if ir.fields.isEmpty {
            if preludeEmitted {
                out += "\n"
            }
            out += "    public init() {}\n"
            out += "\n"
            out += "    public func encode(to encoder: CDREncoder) throws {}\n"
            out += "\n"
            out += "    public init(from decoder: CDRDecoder) throws {}\n"
        } else {
            if preludeEmitted {
                out += "\n"
            }
            for field in ir.fields {
                if let comment = boundedComment(field.type) {
                    out += "    \(comment)\n"
                }
                let typeName = swiftType(field.type, nestedNameOverrides: nestedNameOverrides)
                out += "    public var \(field.swiftName): \(typeName)\n"
            }
            out += "\n"
            if ir.fields.count == 1, let field = ir.fields.first {
                let typeName = swiftType(field.type, nestedNameOverrides: nestedNameOverrides)
                let defaultVal = initDefault(field, nestedNameOverrides: nestedNameOverrides)
                out += "    public init(\(field.swiftName): \(typeName) = \(defaultVal)) {\n"
                out += "        self.\(field.swiftName) = \(field.swiftName)\n"
            } else {
                out += "    public init(\n"
                for (i, field) in ir.fields.enumerated() {
                    let comma = i == ir.fields.count - 1 ? "" : ","
                    let typeName = swiftType(field.type, nestedNameOverrides: nestedNameOverrides)
                    let defaultVal = initDefault(field, nestedNameOverrides: nestedNameOverrides)
                    out += "        \(field.swiftName): \(typeName) = \(defaultVal)\(comma)\n"
                }
                out += "    ) {\n"
                for field in ir.fields {
                    out += "        self.\(field.swiftName) = \(field.swiftName)\n"
                }
            }
            out += "    }\n"
            out += "\n"
            out += "    public func encode(to encoder: CDREncoder) throws {\n"
            for field in ir.fields {
                out += emitEncode(field, nestedNameOverrides: nestedNameOverrides)
            }
            out += "    }\n"
            out += "\n"
            out += "    public init(from decoder: CDRDecoder) throws {\n"
            for field in ir.fields {
                out += emitDecode(field, nestedNameOverrides: nestedNameOverrides)
            }
            out += "    }\n"
        }
        out += "}\n"
        return out
    }

    /// Render a `ROS2ServiceType` umbrella enum that ties the previously-emitted
    /// request / response struct halves together. The umbrella owns the canonical
    /// `<pkg>/srv/<Service>` `serviceName` plus the per-half RIHS01 hashes; the
    /// halves themselves carry their own `<pkg>/srv/<Service>_Request|Response`
    /// `typeInfo` (so they are usable as standalone messages too, which is what
    /// the wire layer hands to publishers / subscriptions internally).
    public static func emitServiceUmbrella(
        package: String,
        serviceTypeName: String,
        umbrellaName: String,
        requestStructName: String,
        responseStructName: String,
        requestHash: String?,
        responseHash: String?,
        sourceLabel: String
    ) -> String {
        var out = ""
        out += "// Generated by swift-ros2-gen \u{2014} DO NOT EDIT.\n"
        out += "// Source: \(sourceLabel)\n"
        out += "\n"
        out += "import SwiftROS2CDR\n"
        out += "\n"
        out += "/// \(package)/srv/\(serviceTypeName)\n"
        out += "public enum \(umbrellaName): ROS2ServiceType {\n"
        out += "    public static let typeInfo = ROS2ServiceTypeInfo(\n"
        out += "        serviceName: \"\(package)/srv/\(serviceTypeName)\",\n"
        out += "        requestTypeName: \"\(package)/srv/\(serviceTypeName)_Request\",\n"
        out += "        responseTypeName: \"\(package)/srv/\(serviceTypeName)_Response\",\n"
        out += "        requestTypeHash: \(swiftOptionalString(requestHash)),\n"
        out += "        responseTypeHash: \(swiftOptionalString(responseHash))\n"
        out += "    )\n"
        out += "\n"
        out += "    public typealias Request = \(requestStructName)\n"
        out += "    public typealias Response = \(responseStructName)\n"
        out += "}\n"
        return out
    }

    private static func swiftOptionalString(_ s: String?) -> String {
        guard let s = s else { return "nil" }
        return "\"\(s)\""
    }

    /// Convention: append `Msg` only when the type name collides with a Swift stdlib name
    /// (or `Empty`, kept for ROS-conventional symmetry with Phase 1). Anything else emits
    /// as bare PascalCase. All generated types coexist in the `SwiftROS2Messages` Swift
    /// module so the bare name is unambiguous.
    public static func swiftStructName(typeName: String) -> String {
        collisionTypeNames.contains(typeName) ? typeName + "Msg" : typeName
    }

    static func swiftType(_ ft: FieldType, nestedNameOverrides: [String: String] = [:]) -> String {
        switch ft {
        case .primitive(let p): return p.swiftTypeName
        case .nested(let pkg, let typeName):
            let key = "\(pkg)/msg/\(typeName)"
            return nestedNameOverrides[key] ?? swiftStructName(typeName: typeName)
        case .array(let element, _):
            return "[\(swiftType(element, nestedNameOverrides: nestedNameOverrides))]"
        case .sequence(let element, _):
            return "[\(swiftType(element, nestedNameOverrides: nestedNameOverrides))]"
        case .boundedString:
            return "String"
        }
    }

    static func swiftDefault(_ ft: FieldType, nestedNameOverrides: [String: String] = [:]) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "false"
            case .byte, .uint8, .char, .int8,
                .int16, .uint16, .int32, .uint32, .int64, .uint64:
                return "0"
            case .float32, .float64: return "0.0"
            case .string, .wstring: return "\"\""
            }
        case .nested(let pkg, let typeName):
            let key = "\(pkg)/msg/\(typeName)"
            let n = nestedNameOverrides[key] ?? swiftStructName(typeName: typeName)
            return "\(n)()"
        case .array(let element, let length):
            let inner = swiftDefault(element, nestedNameOverrides: nestedNameOverrides)
            return "Array(repeating: \(inner), count: \(length))"
        case .sequence:
            return "[]"
        case .boundedString:
            return "\"\""
        }
    }

    /// Pick the init-parameter default. Prefer the parsed `defaultValue` when set; fall back
    /// to the type-shaped zero value.
    static func initDefault(_ field: FieldIR, nestedNameOverrides: [String: String]) -> String {
        if let dv = field.defaultValue, dv != .empty {
            return swiftLiteral(dv)
        }
        return swiftDefault(field.type, nestedNameOverrides: nestedNameOverrides)
    }

    /// Render a typed default as a Swift literal (no surrounding init()).
    static func swiftLiteral(_ dv: DefaultValue) -> String {
        switch dv {
        case .bool(let b): return b ? "true" : "false"
        case .int(let n): return String(n)
        case .uint(let n): return String(n)
        case .float(let d): return String(d)
        case .string(let s): return "\"\(s)\""
        case .empty: return ""
        case .array(let xs):
            return "[" + xs.map(swiftLiteral).joined(separator: ", ") + "]"
        }
    }

    /// `// note: bounded <=N` comment for bounded string / sequence fields.
    static func boundedComment(_ ft: FieldType) -> String? {
        switch ft {
        case .boundedString(_, let upper): return "// note: bounded <=\(upper)"
        case .sequence(_, let upper?): return "// note: bounded <=\(upper)"
        default: return nil
        }
    }

    static func emitEncode(_ field: FieldIR, nestedNameOverrides: [String: String]) -> String {
        switch field.type {
        case .primitive:
            return "        encoder.\(writerCall(field.type))(\(field.swiftName))\n"
        case .nested:
            return "        try \(field.swiftName).encode(to: encoder)\n"
        case .array(let element, _):
            // Fixed array: per-element loop, no length prefix.
            var out = "        for v in \(field.swiftName) {\n"
            out += "            \(elementEncodeStmt(element, value: "v"))\n"
            out += "        }\n"
            return out
        case .sequence(let element, _):
            // Sequence: explicit uint32 length prefix, then per-element loop.
            var out = "        encoder.writeUInt32(UInt32(\(field.swiftName).count))\n"
            out += "        for v in \(field.swiftName) {\n"
            out += "            \(elementEncodeStmt(element, value: "v"))\n"
            out += "        }\n"
            return out
        case .boundedString:
            return "        encoder.writeString(\(field.swiftName))\n"
        }
    }

    static func emitDecode(_ field: FieldIR, nestedNameOverrides: [String: String]) -> String {
        switch field.type {
        case .primitive:
            return "        self.\(field.swiftName) = try decoder.\(readerCall(field.type))()\n"
        case .nested(let pkg, let typeName):
            let key = "\(pkg)/msg/\(typeName)"
            let n = nestedNameOverrides[key] ?? swiftStructName(typeName: typeName)
            return "        self.\(field.swiftName) = try \(n)(from: decoder)\n"
        case .array(let element, let length):
            let elemType = swiftType(element, nestedNameOverrides: nestedNameOverrides)
            var out = "        var out: [\(elemType)] = []\n"
            out += "        out.reserveCapacity(\(length))\n"
            out += "        for _ in 0..<\(length) {\n"
            out += "            out.append(\(elementDecodeExpr(element, nestedNameOverrides: nestedNameOverrides)))\n"
            out += "        }\n"
            out += "        self.\(field.swiftName) = out\n"
            return out
        case .sequence(let element, _):
            let elemType = swiftType(element, nestedNameOverrides: nestedNameOverrides)
            var out = "        let count = try decoder.readSequenceCount()\n"
            out += "        var out: [\(elemType)] = []\n"
            out += "        out.reserveCapacity(count)\n"
            out += "        for _ in 0..<count {\n"
            out += "            out.append(\(elementDecodeExpr(element, nestedNameOverrides: nestedNameOverrides)))\n"
            out += "        }\n"
            out += "        self.\(field.swiftName) = out\n"
            return out
        case .boundedString:
            return "        self.\(field.swiftName) = try decoder.readString()\n"
        }
    }

    /// Encode a single element of an array / sequence.
    static func elementEncodeStmt(_ element: FieldType, value: String) -> String {
        switch element {
        case .primitive:
            return "encoder.\(writerCall(element))(\(value))"
        case .nested:
            return "try \(value).encode(to: encoder)"
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter: nested array/sequence/boundedString elements are not supported")
        }
    }

    /// Decode a single element of an array / sequence into an `.append(...)` argument.
    static func elementDecodeExpr(_ element: FieldType, nestedNameOverrides: [String: String]) -> String {
        switch element {
        case .primitive:
            return "try decoder.\(readerCall(element))()"
        case .nested(let pkg, let typeName):
            let key = "\(pkg)/msg/\(typeName)"
            let n = nestedNameOverrides[key] ?? swiftStructName(typeName: typeName)
            return "try \(n)(from: decoder)"
        case .array, .sequence, .boundedString:
            preconditionFailure(
                "SwiftEmitter: nested array/sequence/boundedString elements are not supported")
        }
    }

    static func writerCall(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "writeBool"
            case .byte, .uint8: return "writeUInt8"
            case .char, .int8: return "writeInt8"
            case .int16: return "writeInt16"
            case .uint16: return "writeUInt16"
            case .int32: return "writeInt32"
            case .uint32: return "writeUInt32"
            case .int64: return "writeInt64"
            case .uint64: return "writeUInt64"
            case .float32: return "writeFloat32"
            case .float64: return "writeFloat64"
            case .string, .wstring: return "writeString"
            }
        case .nested:
            preconditionFailure("writerCall is not defined for nested types — use emitEncode")
        case .array, .sequence, .boundedString:
            preconditionFailure("writerCall is not defined for array/sequence/boundedString")
        }
    }

    static func readerCall(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "readBool"
            case .byte, .uint8: return "readUInt8"
            case .char, .int8: return "readInt8"
            case .int16: return "readInt16"
            case .uint16: return "readUInt16"
            case .int32: return "readInt32"
            case .uint32: return "readUInt32"
            case .int64: return "readInt64"
            case .uint64: return "readUInt64"
            case .float32: return "readFloat32"
            case .float64: return "readFloat64"
            case .string, .wstring: return "readString"
            }
        case .nested:
            preconditionFailure("readerCall is not defined for nested types — use emitDecode")
        case .array, .sequence, .boundedString:
            preconditionFailure("readerCall is not defined for array/sequence/boundedString")
        }
    }
}
