public enum SwiftEmitter {
    public static func emit(_ ir: MessageIR, sourceLabel: String) -> String {
        var out = ""
        out += "// Generated by swift-ros2-gen \u{2014} DO NOT EDIT.\n"
        out += "// Source: \(sourceLabel)\n"
        out += "\n"
        out += "import SwiftROS2CDR\n"
        out += "\n"
        out += "/// \(ir.rosTypeName)\n"
        let structName = swiftStructName(typeName: ir.typeName)
        out += "public struct \(structName): ROS2Message, Equatable, Sendable {\n"
        let hash = ir.perDistroHashes["jazzy"] ?? ""
        out += "    public static let typeInfo = ROS2MessageTypeInfo(\n"
        out += "        typeName: \"\(ir.rosTypeName)\",\n"
        out += "        typeHash: \"\(hash)\"\n"
        out += "    )\n"
        out += "\n"
        if ir.fields.isEmpty {
            out += "    public init() {}\n"
            out += "\n"
            out += "    public func encode(to encoder: CDREncoder) throws {\n"
            out += "        encoder.writeEncapsulationHeader()\n"
            out += "    }\n"
            out += "\n"
            out += "    public init(from decoder: CDRDecoder) throws {}\n"
        } else {
            for field in ir.fields {
                out += "    public var \(field.swiftName): \(swiftType(field.type))\n"
            }
            out += "\n"
            if ir.fields.count == 1, let field = ir.fields.first {
                out += "    public init(\(field.swiftName): \(swiftType(field.type)) = \(swiftDefault(field.type))) {\n"
                out += "        self.\(field.swiftName) = \(field.swiftName)\n"
            } else {
                out += "    public init(\n"
                for (i, field) in ir.fields.enumerated() {
                    let comma = i == ir.fields.count - 1 ? "" : ","
                    let typeName = swiftType(field.type)
                    let defaultVal = swiftDefault(field.type)
                    out += "        \(field.swiftName): \(typeName) = \(defaultVal)\(comma)\n"
                }
                out += "    ) {\n"
                for field in ir.fields {
                    out += "        self.\(field.swiftName) = \(field.swiftName)\n"
                }
            }
            out += "    }\n"
            out += "\n"
            out += "    public func encode(to encoder: CDREncoder) throws {\n"
            out += "        encoder.writeEncapsulationHeader()\n"
            for field in ir.fields {
                out += "        encoder.\(writerCall(field.type))(\(field.swiftName))\n"
            }
            out += "    }\n"
            out += "\n"
            out += "    public init(from decoder: CDRDecoder) throws {\n"
            for field in ir.fields {
                out += "        self.\(field.swiftName) = try decoder.\(readerCall(field.type))()\n"
            }
            out += "    }\n"
        }
        out += "}\n"
        return out
    }

    /// Convention: append "Msg" to type names that collide with Swift stdlib
    /// or ROS-conventional aliases. Phase 1 always appends; the rule is
    /// revisited when geometry_msgs (with non-clashing names like `Vector3`)
    /// lands in Phase 2.
    public static func swiftStructName(typeName: String) -> String {
        typeName + "Msg"
    }

    static func swiftType(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p): return p.swiftTypeName
        }
    }

    static func swiftDefault(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "false"
            case .byte, .uint8, .char, .int8,
                .int16, .uint16, .int32, .uint32, .int64, .uint64:
                return "0"
            case .float32, .float64: return "0.0"
            case .string, .wstring: return "\"\""
            }
        }
    }

    static func writerCall(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "writeBool"
            case .byte, .uint8: return "writeUInt8"
            case .char, .int8: return "writeInt8"
            case .int16: return "writeInt16"
            case .uint16: return "writeUInt16"
            case .int32: return "writeInt32"
            case .uint32: return "writeUInt32"
            case .int64: return "writeInt64"
            case .uint64: return "writeUInt64"
            case .float32: return "writeFloat32"
            case .float64: return "writeFloat64"
            case .string, .wstring: return "writeString"
            }
        }
    }

    static func readerCall(_ ft: FieldType) -> String {
        switch ft {
        case .primitive(let p):
            switch p {
            case .bool: return "readBool"
            case .byte, .uint8: return "readUInt8"
            case .char, .int8: return "readInt8"
            case .int16: return "readInt16"
            case .uint16: return "readUInt16"
            case .int32: return "readInt32"
            case .uint32: return "readUInt32"
            case .int64: return "readInt64"
            case .uint64: return "readUInt64"
            case .float32: return "readFloat32"
            case .float64: return "readFloat64"
            case .string, .wstring: return "readString"
            }
        }
    }
}
