// Generated by swift-ros2-gen — DO NOT EDIT.

#ifndef CRCL_MARSHAL_H
#define CRCL_MARSHAL_H

#include <rosidl_runtime_c/message_type_support_struct.h>

#include "Generated/crcl_marshal_battery_state.h"
#include "Generated/crcl_marshal_compressed_image.h"
#include "Generated/crcl_marshal_fluid_pressure.h"
#include "Generated/crcl_marshal_illuminance.h"
#include "Generated/crcl_marshal_imu.h"
#include "Generated/crcl_marshal_joy.h"
#include "Generated/crcl_marshal_magnetic_field.h"
#include "Generated/crcl_marshal_nav_sat_fix.h"
#include "Generated/crcl_marshal_point_cloud2.h"
#include "Generated/crcl_marshal_range.h"
#include "Generated/crcl_marshal_temperature.h"

#ifdef __cplusplus
extern "C" {
#endif

const rosidl_message_type_support_t *crcl_marshal_resolve_typesupport(const char *name);

#ifdef __cplusplus
}
#endif
#endif  // CRCL_MARSHAL_H
