// Generated by swift-ros2-gen — DO NOT EDIT.

#ifndef CRCL_MARSHAL_H
#define CRCL_MARSHAL_H

#include <rosidl_runtime_c/message_type_support_struct.h>

#include "Generated/crcl_marshal_imu.h"

#ifdef __cplusplus
extern "C" {
#endif

const rosidl_message_type_support_t *crcl_marshal_resolve_typesupport(const char *name);

#ifdef __cplusplus
}
#endif
#endif  // CRCL_MARSHAL_H
