import Testing

@testable import SwiftROS2Gen

@Suite("RclMarshalSwiftEmitter — per-type Swift unpacker source")
struct RclMarshalSwiftEmitterTests {
    private func emit(_ rosTypeName: String) throws -> String {
        let registry = try TestIR.sensorMsgsRegistry()
        let ir = try #require(registry[rosTypeName])
        return RclMarshalSwiftEmitter.emit(ir, registry: registry)
    }

    @Test("emits Imu unpacker surface + imports")
    func emitsImu() throws {
        let s = try emit("sensor_msgs/msg/Imu")
        // Banner + four alphabetized imports.
        #expect(s.contains("// Generated by swift-ros2-gen"))
        #expect(s.contains("import CRclBridge"))
        #expect(s.contains("import Foundation"))
        #expect(s.contains("import SwiftROS2Messages"))
        #expect(s.contains("import SwiftROS2Transport"))
        // Serialize free function + extension conformance.
        #expect(s.contains("package func rclSerializeImu(_ value: Imu) throws -> [UInt8]"))
        #expect(s.contains("extension Imu: RclTypedPublishable"))
        #expect(s.contains("crcl_serialize_imu("))
        #expect(s.contains("crcl_publish_imu("))
        // Fixed-array covariance unpacked via withUnsafeBufferPointer.
        #expect(s.contains("value.orientationCovariance.withUnsafeBufferPointer"))
        // Fixed arrays are length-guarded before the base pointer is handed to C.
        #expect(s.contains("precondition(value.orientationCovariance.count == 9"))
        // No struct-array helper for Imu (no string sequence members).
        #expect(!s.contains("withCStringArray("))
    }

    @Test("emits Joy scalar-sequence unpack")
    func emitsJoy() throws {
        let s = try emit("sensor_msgs/msg/Joy")
        #expect(s.contains("value.axes.withUnsafeBufferPointer"))
        #expect(s.contains("value.buttons.withUnsafeBufferPointer"))
        #expect(s.contains("crcl_serialize_joy("))
        #expect(s.contains("crcl_publish_joy("))
    }

    @Test("emits PointCloud2 struct-sequence (SoA + C-string array)")
    func emitsPointCloud2() throws {
        let s = try emit("sensor_msgs/msg/PointCloud2")
        // The C-string-array helper is emitted exactly once.
        #expect(s.contains("withCStringArray("))
        #expect(s.contains("private func withCStringArray<R>("))
        // Parallel struct-of-arrays mapping over a PointField member.
        #expect(s.contains(".map { $0.offset }"))
        #expect(s.contains("crcl_publish_point_cloud2("))
        #expect(s.contains("crcl_serialize_point_cloud2("))
        // Every opened brace is closed: the nested-closure composition balances.
        #expect(s.filter { $0 == "{" }.count == s.filter { $0 == "}" }.count)
    }

    @Test("emits BatteryState two-sequence unpack with distinct buffer names")
    func emitsBatteryState() throws {
        let s = try emit("sensor_msgs/msg/BatteryState")
        // Two parallel [Float] sequences get distinct, paramName-derived buffers
        // (lowerCamelCased so the generated Swift passes swift-format lint).
        #expect(s.contains("cellVoltageBuf"))
        #expect(s.contains("cellTemperatureBuf"))
        #expect(s.contains("crcl_serialize_battery_state("))
        #expect(s.contains("crcl_publish_battery_state("))
        // Brace balance across the two-opener nesting.
        #expect(s.filter { $0 == "{" }.count == s.filter { $0 == "}" }.count)
    }
}
