// Generated by swift-ros2-gen — DO NOT EDIT.
// Source: action_msgs/msg/GoalStatus.msg

import SwiftROS2CDR

/// action_msgs/msg/GoalStatus
public struct GoalStatus: CDRCodable, Equatable, Sendable {
    // swift-format-ignore: AlwaysUseLowerCamelCase
    public static let STATUS_UNKNOWN: Int8 = 0
    // swift-format-ignore: AlwaysUseLowerCamelCase
    public static let STATUS_ACCEPTED: Int8 = 1
    // swift-format-ignore: AlwaysUseLowerCamelCase
    public static let STATUS_EXECUTING: Int8 = 2
    // swift-format-ignore: AlwaysUseLowerCamelCase
    public static let STATUS_CANCELING: Int8 = 3
    // swift-format-ignore: AlwaysUseLowerCamelCase
    public static let STATUS_SUCCEEDED: Int8 = 4
    // swift-format-ignore: AlwaysUseLowerCamelCase
    public static let STATUS_CANCELED: Int8 = 5
    // swift-format-ignore: AlwaysUseLowerCamelCase
    public static let STATUS_ABORTED: Int8 = 6

    public var goalInfo: GoalInfo
    public var status: Int8

    public init(
        goalInfo: GoalInfo = GoalInfo(),
        status: Int8 = 0
    ) {
        self.goalInfo = goalInfo
        self.status = status
    }

    public func encode(to encoder: CDREncoder) throws {
        try goalInfo.encode(to: encoder)
        encoder.writeInt8(status)
    }

    public init(from decoder: CDRDecoder) throws {
        self.goalInfo = try GoalInfo(from: decoder)
        self.status = try decoder.readInt8()
    }
}
