// Generated by swift-ros2-gen — DO NOT EDIT.
// Source: common_interfaces-jazzy/std_msgs/msg/Int32.msg

import SwiftROS2CDR

/// std_msgs/msg/Int32
public struct Int32Msg: ROS2Message, Equatable, Sendable {
    public static let typeInfo = ROS2MessageTypeInfo(
        typeName: "std_msgs/msg/Int32",
        typeHash: "RIHS01_b6578ded3c58c626cfe8d1a6fb6e04f706f97e9f03d2727c9ff4e74b1cef0deb"
    )

    public var data: Int32

    public init(data: Int32 = 0) {
        self.data = data
    }

    public func encode(to encoder: CDREncoder) throws {
        encoder.writeEncapsulationHeader()
        encoder.writeInt32(data)
    }

    public init(from decoder: CDRDecoder) throws {
        self.data = try decoder.readInt32()
    }
}
