// Generated by swift-ros2-gen — DO NOT EDIT.
// Source: common_interfaces-jazzy/std_msgs/msg/String.msg

import SwiftROS2CDR

/// std_msgs/msg/String
public struct StringMsg: ROS2Message, Equatable, Sendable {
    public static let typeInfo = ROS2MessageTypeInfo(
        typeName: "std_msgs/msg/String",
        typeHash: "RIHS01_df668c740482bbd48fb39d76a70dfd4bd59db1288021743503259e948f6b1a18"
    )

    public var data: String

    public init(data: String = "") {
        self.data = data
    }

    public func encode(to encoder: CDREncoder) throws {
        encoder.writeEncapsulationHeader()
        encoder.writeString(data)
    }

    public init(from decoder: CDRDecoder) throws {
        self.data = try decoder.readString()
    }
}
