// Generated by swift-ros2-gen — DO NOT EDIT.
// Source: common_interfaces-jazzy/geometry_msgs/msg/Vector3.msg

import SwiftROS2CDR

/// geometry_msgs/msg/Vector3
public struct Vector3: ROS2Message, Equatable, Sendable {
    public static let typeInfo = ROS2MessageTypeInfo(
        typeName: "geometry_msgs/msg/Vector3",
        typeHash: "RIHS01_cc12fe83e4c02719f1ce8070bfd14aecd40f75a96696a67a2a1f37f7dbb0765d"
    )

    public var x: Double
    public var y: Double
    public var z: Double

    public init(
        x: Double = 0.0,
        y: Double = 0.0,
        z: Double = 0.0
    ) {
        self.x = x
        self.y = y
        self.z = z
    }

    public func encode(to encoder: CDREncoder) throws {
        encoder.writeFloat64(x)
        encoder.writeFloat64(y)
        encoder.writeFloat64(z)
    }

    public init(from decoder: CDRDecoder) throws {
        self.x = try decoder.readFloat64()
        self.y = try decoder.readFloat64()
        self.z = try decoder.readFloat64()
    }
}
